// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migrations_bd;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Migrations_bd.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210924161518_365")]
    partial class _365
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Migrations_bd.gar_address_objects", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CHANGEID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ENDDATE")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ISACTIVE")
                        .HasColumnType("integer");

                    b.Property<int>("ISACTUAL")
                        .HasColumnType("integer");

                    b.Property<string>("LEVEL")
                        .HasColumnType("text");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.Property<long>("NEXTID")
                        .HasColumnType("bigint");

                    b.Property<string>("OBJECTGUID")
                        .HasColumnType("text");

                    b.Property<long>("OBJECTID")
                        .HasColumnType("bigint");

                    b.Property<string>("OPERTYPEID")
                        .HasColumnType("text");

                    b.Property<long>("PREVID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("STARTDATE")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TYPENAME")
                        .HasColumnType("text");

                    b.Property<DateTime>("UPDATEDATE")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("gar_AddObjCon");
                });

            modelBuilder.Entity("Migrations_bd.gar_adm_hier", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("aREACODE")
                        .HasColumnType("text");

                    b.Property<long>("cHANGEID")
                        .HasColumnType("bigint");

                    b.Property<string>("cITYCODE")
                        .HasColumnType("text");

                    b.Property<DateTime>("eNDDATE")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("iSACTIVE")
                        .HasColumnType("integer");

                    b.Property<long>("nEXTID")
                        .HasColumnType("bigint");

                    b.Property<long>("oBJECTID")
                        .HasColumnType("bigint");

                    b.Property<long>("pARENTOBJID")
                        .HasColumnType("bigint");

                    b.Property<string>("pLACECODE")
                        .HasColumnType("text");

                    b.Property<string>("pLANCODE")
                        .HasColumnType("text");

                    b.Property<long>("pREVID")
                        .HasColumnType("bigint");

                    b.Property<string>("rEGIONCODE")
                        .HasColumnType("text");

                    b.Property<DateTime>("sTARTDATE")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("sTREETCODE")
                        .HasColumnType("text");

                    b.Property<DateTime>("uPDATEDATE")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.ToTable("gar_AdmHierCon");
                });

            modelBuilder.Entity("Migrations_bd.gar_houses", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("aDDNUM1")
                        .HasColumnType("text");

                    b.Property<string>("aDDNUM2")
                        .HasColumnType("text");

                    b.Property<string>("aDDTYPE1")
                        .HasColumnType("text");

                    b.Property<string>("aDDTYPE2")
                        .HasColumnType("text");

                    b.Property<long>("cHANGEID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("eNDDATE")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("hOUSENUM")
                        .HasColumnType("text");

                    b.Property<string>("hOUSETYPE")
                        .HasColumnType("text");

                    b.Property<int>("iSACTIVE")
                        .HasColumnType("integer");

                    b.Property<int>("iSACTUAL")
                        .HasColumnType("integer");

                    b.Property<long>("nEXTID")
                        .HasColumnType("bigint");

                    b.Property<string>("oBJECTGUID")
                        .HasColumnType("text");

                    b.Property<long>("oBJECTID")
                        .HasColumnType("bigint");

                    b.Property<string>("oPERTYPEID")
                        .HasColumnType("text");

                    b.Property<long>("pREVID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("sTARTDATE")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("uPDATEDATE")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.ToTable("gar_HousesCon");
                });
#pragma warning restore 612, 618
        }
    }
}
