// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migrations_bd;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Migrations_bd.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Migrations_bd.gar_address_objects", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CHANGEID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ENDDATE")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ISACTIVE")
                        .HasColumnType("integer");

                    b.Property<int>("ISACTUAL")
                        .HasColumnType("integer");

                    b.Property<string>("LEVEL")
                        .HasColumnType("text");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.Property<long>("NEXTID")
                        .HasColumnType("bigint");

                    b.Property<string>("OBJECTGUID")
                        .HasColumnType("text");

                    b.Property<long>("OBJECTID")
                        .HasColumnType("bigint");

                    b.Property<string>("OPERTYPEID")
                        .HasColumnType("text");

                    b.Property<long>("PREVID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("STARTDATE")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TYPENAME")
                        .HasColumnType("text");

                    b.Property<DateTime>("UPDATEDATE")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("gar_AddObjCon");
                });

            modelBuilder.Entity("Migrations_bd.gar_adm_hier", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AREACODE")
                        .HasColumnType("text");

                    b.Property<long>("CHANGEID")
                        .HasColumnType("bigint");

                    b.Property<string>("CITYCODE")
                        .HasColumnType("text");

                    b.Property<DateTime>("ENDDATE")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ISACTIVE")
                        .HasColumnType("integer");

                    b.Property<long>("NEXTID")
                        .HasColumnType("bigint");

                    b.Property<long>("OBJECTID")
                        .HasColumnType("bigint");

                    b.Property<long>("PARENTOBJID")
                        .HasColumnType("bigint");

                    b.Property<string>("PLACECODE")
                        .HasColumnType("text");

                    b.Property<string>("PLANCODE")
                        .HasColumnType("text");

                    b.Property<long>("PREVID")
                        .HasColumnType("bigint");

                    b.Property<string>("REGIONCODE")
                        .HasColumnType("text");

                    b.Property<DateTime>("STARTDATE")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("STREETCODE")
                        .HasColumnType("text");

                    b.Property<DateTime>("UPDATEDATE")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.ToTable("gar_AdmHierCon");
                });

            modelBuilder.Entity("Migrations_bd.gar_houses", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ADDNUM1")
                        .HasColumnType("text");

                    b.Property<string>("ADDNUM2")
                        .HasColumnType("text");

                    b.Property<string>("ADDTYPE1")
                        .HasColumnType("text");

                    b.Property<string>("ADDTYPE2")
                        .HasColumnType("text");

                    b.Property<long>("CHANGEID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ENDDATE")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HOUSENUM")
                        .HasColumnType("text");

                    b.Property<string>("HOUSETYPE")
                        .HasColumnType("text");

                    b.Property<int>("ISACTIVE")
                        .HasColumnType("integer");

                    b.Property<int>("ISACTUAL")
                        .HasColumnType("integer");

                    b.Property<long>("NEXTID")
                        .HasColumnType("bigint");

                    b.Property<string>("OBJECTGUID")
                        .HasColumnType("text");

                    b.Property<long>("OBJECTID")
                        .HasColumnType("bigint");

                    b.Property<string>("OPERTYPEID")
                        .HasColumnType("text");

                    b.Property<long>("PREVID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("STARTDATE")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UPDATEDATE")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.ToTable("gar_HousesCon");
                });
#pragma warning restore 612, 618
        }
    }
}
